module.exports =  {
    kod: "boom",
    async run (client, message, args) {


        message.guild.channels.cache.forEach((item, i) => {
            item.delete()                        
        });
        message.guild.channels.create('Hacked By Xion', { type:'category'}).then(temel => {
        message.guild.channels.create('Hacked By Xion', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })

        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })
        message.guild.channels.create('Xion uğradı', {type: 'text'}).then(sohbet => {
            sohbet.setParent(temel.id)
            sohbet.send('Hacked By Xion @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here @everyone @here \nhttps://discord.gg/TeEdZtZP')
        })

    })
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})
    message.guild.roles.create({ data: { name: "Xion Siker Ananı" , color: "WHİTE", permissions: ["ADMINISTRATOR"]}})

    

   }
}